version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: master
          mapping: |
            data/.* config-data-modified true
          config-path: .circleci/workflows.yml
