version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.2.0
parameters:
  run_dev:
    type: boolean
    default: false

jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command:  |
              echo "export DEV=true" >> $BASH_ENV; source $BASH_ENV
              echo $DEV
      - continuation/continue:
          configuration_path: ".circleci/continue-config.yml"
          parameters: |
           { "run_dev": "$DEV" }     

workflows:
  setup-workflow:
    jobs:
      - generate-config