version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                command: |
                    chmod +x circleci/commit_check.sh &&  .circleci/commit_check.sh
