version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                command: |
                        CHANGE_CHECKER=./script_checker.py
                        SUB_DIR=./K8
                        if [[ `python3 ${CHANGE_CHECKER} ${SUB_DIR}` == "True" ]]; then
                            # run unit tests against ${SUB_DIR}
                        fi
