version: 2
parameters:
    workingdir:
        type: boolean
        default: false
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                command: |
                        CHANGE_CHECKER=./.circleci/script_checker.py
                        SUB_DIR=./K8
                        if [[ `python3 ${CHANGE_CHECKER} ${SUB_DIR}` == "True" ]]
                        then
                            echo "<< pipeline.parameters.workingdir >> = TRUE"
                        fi
            - run: echo << pipeline.parameters.workingdir >>
