version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                command: |
                        CHANGE_CHECKER=./.circleci/script_checker.py
                        SUB_DIR=./K8
                        if [ python3 ./.circleci/script_checker.py  ./K8 == "True" ]
                        then
                            echo "a"
                        fi
