version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.2.0
parameters:
  run_dev:
    type: boolean
    default: false

jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command:  |
              echo "export ENV=true" >> $BASH_ENV; source $BASH_ENV
              echo $ENV
      - run:
          command: |
              ./.circleci/generator.sh $ENV 

      - continuation/continue:
          configuration_path: ".circleci/main.yml"  

workflows:
  setup-workflow:
    jobs:
      - generate-config