version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.2.0
parameters:
  run_dev:
    type: boolean
    default: false

jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command:  echo 'export DEV=true' >> $BASH_ENV
      - continuation/continue:
          configuration_path: ".circleci/test.yml"
          parameters: |
           { "pathtodev":"$DEV" } 
          requires:
            - run
          pre-steps:
            -checkout         

workflows:
  setup:
    jobs:
      - generate-config