version: '2.1'

parameters:
  build-code:
    type: boolean
    default: false
  build-docs:
    type: boolean
    default: false

workflows:
  build-code-workflow:
    when: << pipeline.parameters.build-code >>
    jobs:
      shellcheck:
        docker:
          - image: circleci/python:3.9.6
         steps:
            - checkout
            - run:
                name: Check
                command: ls
                
  build-docs-workflow:
    when: << pipeline.parameters.build-docs >>
    jobs:
      - build-docs-job
