version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0
  docker: circleci/docker@1.5.0

parameters:
  config-data-modified:
    type: boolean
    default: false
  service-layer-modified:
    type: boolean
    default: false
  run-site-api-workflow:
    type: boolean
    default: false
  run-batch-services-workflow:
    type: boolean
    default: false
  run-site-ui-workflow:
    type: boolean
    default: false
  run-admin-ui-workflow:
    type: boolean
    default: false
  run-azure-functions-workflow:
    type: boolean
    default: false
  run-product-classifier-api-workflow:
    type: boolean
    default: false

commands:
  azure-cli-install-login:
    steps:
      - run:
          name: install azure cli
          command: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - azure-cli/login-with-service-principal
  azure-functions-core-tools-install:
    steps:
      - run:
          name: install azure functions core tools
          command: |
            curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
            sudo apt update
            sudo apt install -y --no-install-recommends azure-functions-core-tools-3

jobs:
  build-site-api:
    docker:
      # next-gen ubuntu image with java 11.0.10
      - image: cimg/openjdk:11.0.10
    resource_class: small
    steps:
      - checkout
      - run:
          name: build site-api
          command: echo "Hello!"


workflows:
  site-api:
    when:
      or:
        - << pipeline.parameters.run-site-api-workflow >>
        - << pipeline.parameters.service-layer-modified >>
        - << pipeline.parameters.config-data-modified >>
    jobs:
      - build-site-api
